### ISSUE TITLE
Error on ./build-s3-dist.sh

### ISSUE THREAD

**Issue by sunilvrao** [aws-solutions/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk#47]
I am following this link https://github.com/aws-solutions/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk/blob/main/README.md

I am on step 3.  

./build-s3-dist.sh <<bucket>> <<solution>> <<version>>

I get this error.

------------------------------------------------------------------------------
[Init] Remove any old dist files from previous runs
------------------------------------------------------------------------------
------------------------------------------------------------------------------
[Init] Get version of the AWS CDK
------------------------------------------------------------------------------
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '<<<local dir path >>>/deployment/get-cdk-version.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by dscpinheiro** [comment]
Hi @sunilvrao,

Thanks for reporting the issue, there was a missing file which we added it in https://github.com/aws-solutions/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk/pull/48.
